// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

import type { Metadata } from "next";
import { Inter } from "next/font/google"; // Or your preferred font
import "./globals.css";

// 1. Import your components
// Adjust the path '../components/' based on where you saved them
import Navbar from "@/components/Navbar"; 
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    default: "ShopHub | Premium Tech Gear",
    template: "%s | ShopHub", // This adds "| ShopHub" to every page title automatically
  },
  description: "The best place to buy modern electronics, gadgets, and fashion. Fast shipping and secure checkout.",
  openGraph: {
    title: "ShopHub | Premium Tech Gear",
    description: "Upgrade your lifestyle with the latest tech and fashion.",
    url: "https://shophub-demo.vercel.app", // Replace with your real URL later
    siteName: "ShopHub",
    images: [
      {
        url: "https://images.unsplash.com/photo-1498049860654-af1a5c5668ba?auto=format&fit=crop&w=1200&q=80", // A generic banner image
        width: 1200,
        height: 630,
      },
    ],
    locale: "en_US",
    type: "website",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen flex flex-col bg-slate-50 dark:bg-slate-950`}>
        
        {/* 2. The Navbar sits at the top */}
        <Navbar />
        
        {/* 3. The Main Content */}
        {/* - flex-grow: Pushes the Footer to the bottom even if content is short
            - pt-20: Adds top padding so the fixed Navbar doesn't cover your content
        */}
        <main className="flex-grow pt-20">
          {children}
        </main>

        {/* 4. The Footer sits at the bottom */}
        <Footer />
        
      </body>
    </html>
  );
}